/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package terceiraquestao;



/**
 *
 * @author pedro
 */
public class calculadorapesos extends javax.swing.JFrame {

    /**
     * Creates new form calculadorapesos
     */
    public calculadorapesos() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        peso = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rotulo1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        marte = new javax.swing.JRadioButton();
        mercurio = new javax.swing.JRadioButton();
        venus = new javax.swing.JRadioButton();
        saturno = new javax.swing.JRadioButton();
        urano = new javax.swing.JRadioButton();
        jupiter = new javax.swing.JRadioButton();
        resposta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Selecione o Planeta desejado:");

        rotulo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotulo1.setText("Qual é o seu peso em cada planeta?");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Escreva o peso em kg:");

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        buttonGroup1.add(marte);
        marte.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        marte.setText("Marte");
        marte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marteActionPerformed(evt);
            }
        });

        buttonGroup1.add(mercurio);
        mercurio.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mercurio.setText("Mercúrio");
        mercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mercurioActionPerformed(evt);
            }
        });

        buttonGroup1.add(venus);
        venus.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        venus.setText("Vênus");
        venus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venusActionPerformed(evt);
            }
        });

        buttonGroup1.add(saturno);
        saturno.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        saturno.setText("Saturno");
        saturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturnoActionPerformed(evt);
            }
        });

        buttonGroup1.add(urano);
        urano.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        urano.setText("Urano");
        urano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uranoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jupiter);
        jupiter.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jupiter.setText("Júpiter");
        jupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupiterActionPerformed(evt);
            }
        });

        resposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Peso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(rotulo1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mercurio)
                                        .addGap(8, 8, 8)
                                        .addComponent(marte))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(venus)
                                        .addGap(18, 18, 18)
                                        .addComponent(jupiter))
                                    .addComponent(calcular))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saturno)
                                    .addComponent(urano)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(limpar))
                            .addComponent(resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotulo1)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marte)
                    .addComponent(saturno)
                    .addComponent(mercurio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urano)
                    .addComponent(jupiter)
                    .addComponent(venus))
                .addGap(18, 18, 18)
                .addComponent(calcular)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double p;
    double mer, mar, sat, ven, jup, ura;
    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        peso.setText(null);
        resposta.setText(null);
        peso.requestFocus();
        
        
    }//GEN-LAST:event_limparActionPerformed

    private void mercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mercurioActionPerformed
        // TODO add your handling code here:
        mer = Double.parseDouble(peso.getText());
        p = mer * 0.37;
        
        
    }//GEN-LAST:event_mercurioActionPerformed

    private void marteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marteActionPerformed
        // TODO add your handling code here:
        mar = Double.parseDouble(peso.getText());
        p = mar * 0.38;
        
    }//GEN-LAST:event_marteActionPerformed

    private void saturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturnoActionPerformed
        // TODO add your handling code here:
        sat = Double.parseDouble(peso.getText());
        p = sat * 1.15;
        
    }//GEN-LAST:event_saturnoActionPerformed

    private void venusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venusActionPerformed
        // TODO add your handling code here:
        ven = Double.parseDouble(peso.getText());
        p = ven * 0.88;
        
    }//GEN-LAST:event_venusActionPerformed

    private void jupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupiterActionPerformed
        // TODO add your handling code here:
        jup = Double.parseDouble(peso.getText());
        p = jup * 2.64;
        
    }//GEN-LAST:event_jupiterActionPerformed

    private void uranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uranoActionPerformed
        // TODO add your handling code here:
        ura = Double.parseDouble(peso.getText());
        p = ura * 1.17;
        
    }//GEN-LAST:event_uranoActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        resposta.setText("" + p +"kg");
        
        calcular.setToolTipText("Fará a conversão de peso");
    }//GEN-LAST:event_calcularActionPerformed

    private void respostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respostaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadorapesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadorapesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadorapesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadorapesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadorapesos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jupiter;
    public javax.swing.JButton limpar;
    private javax.swing.JRadioButton marte;
    private javax.swing.JRadioButton mercurio;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField resposta;
    private javax.swing.JLabel rotulo1;
    private javax.swing.JRadioButton saturno;
    private javax.swing.JRadioButton urano;
    private javax.swing.JRadioButton venus;
    // End of variables declaration//GEN-END:variables
}
