
import java.awt.Color;
import java.awt.Font;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        Limpar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        Preto = new javax.swing.JRadioButtonMenuItem();
        azul = new javax.swing.JRadioButtonMenuItem();
        marrom = new javax.swing.JRadioButtonMenuItem();
        rosa = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        normal = new javax.swing.JCheckBoxMenuItem();
        Negrito = new javax.swing.JCheckBoxMenuItem();
        italico = new javax.swing.JCheckBoxMenuItem();
        negritalico = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        t12 = new javax.swing.JCheckBoxMenuItem();
        t14 = new javax.swing.JCheckBoxMenuItem();
        t16 = new javax.swing.JCheckBoxMenuItem();
        t18 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto.setColumns(20);
        texto.setRows(5);
        texto.setText("Digite aqui");
        jScrollPane1.setViewportView(texto);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Editor de Texto");

        jMenu3.setText("Opções");

        Limpar.setText("Limpar");
        Limpar.setToolTipText("");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        jMenu3.add(Limpar);

        jMenu4.setText("Fonte");

        jMenu1.setText("Cor");

        buttonGroup1.add(Preto);
        Preto.setSelected(true);
        Preto.setText("Preto");
        Preto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PretoActionPerformed(evt);
            }
        });
        jMenu1.add(Preto);

        buttonGroup1.add(azul);
        azul.setForeground(new java.awt.Color(51, 51, 255));
        azul.setText("Azul");
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });
        jMenu1.add(azul);

        buttonGroup1.add(marrom);
        marrom.setForeground(new java.awt.Color(150, 75, 0));
        marrom.setText("Marrom");
        marrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marromActionPerformed(evt);
            }
        });
        jMenu1.add(marrom);

        buttonGroup1.add(rosa);
        rosa.setForeground(new java.awt.Color(255, 192, 203));
        rosa.setText("Rosa");
        rosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rosaActionPerformed(evt);
            }
        });
        jMenu1.add(rosa);

        jMenu4.add(jMenu1);

        jMenu2.setText("Estilo");

        buttonGroup2.add(normal);
        normal.setSelected(true);
        normal.setText("Normal");
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });
        jMenu2.add(normal);

        buttonGroup2.add(Negrito);
        Negrito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Negrito.setText("Negrito");
        Negrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegritoActionPerformed(evt);
            }
        });
        jMenu2.add(Negrito);

        buttonGroup2.add(italico);
        italico.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        italico.setText("Itálico");
        italico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italicoActionPerformed(evt);
            }
        });
        jMenu2.add(italico);

        buttonGroup2.add(negritalico);
        negritalico.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        negritalico.setText("Negrito+Italico");
        negritalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negritalicoActionPerformed(evt);
            }
        });
        jMenu2.add(negritalico);

        jMenu4.add(jMenu2);

        jMenu5.setText("Tamanho");

        t12.setSelected(true);
        t12.setText("12");
        t12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t12ActionPerformed(evt);
            }
        });
        jMenu5.add(t12);

        t14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t14.setText("14");
        t14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t14ActionPerformed(evt);
            }
        });
        jMenu5.add(t14);

        t16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t16.setText("16");
        t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t16ActionPerformed(evt);
            }
        });
        jMenu5.add(t16);

        t18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        t18.setText("18");
        t18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t18ActionPerformed(evt);
            }
        });
        jMenu5.add(t18);

        jMenu4.add(jMenu5);

        jMenu3.add(jMenu4);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(186, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    int tam = 12;
    int fonte;
    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here: 
        texto.setText(null);
        texto.requestFocus();
    }//GEN-LAST:event_LimparActionPerformed

    private void rosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rosaActionPerformed
        // TODO add your handling code here:
        texto.setForeground(new Color(255, 192, 203));
        
    }//GEN-LAST:event_rosaActionPerformed

    private void marromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marromActionPerformed
        // TODO add your handling code here:
        texto.setForeground(new Color(150,75,0));
        
    }//GEN-LAST:event_marromActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        // TODO add your handling code here:
        texto.setForeground(new Color(51,51,255));
        
    }//GEN-LAST:event_azulActionPerformed

    private void PretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PretoActionPerformed
        texto.setForeground(Color.black);
        
    }//GEN-LAST:event_PretoActionPerformed

    private void t12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t12ActionPerformed
        tam = 12;
        texto.setFont(new Font("",fonte,tam));
    }//GEN-LAST:event_t12ActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        fonte = Font.PLAIN;
        texto.setFont(new Font("",fonte,tam));
    }//GEN-LAST:event_normalActionPerformed

    private void t14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t14ActionPerformed
        tam = 14;
        texto.setFont(new Font("",fonte,tam));
    }//GEN-LAST:event_t14ActionPerformed

    private void t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t16ActionPerformed
        tam = 16;
        texto.setFont(new Font("",fonte,tam));
    }//GEN-LAST:event_t16ActionPerformed

    private void t18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t18ActionPerformed
        tam = 18;
        texto.setFont(new Font("",fonte,tam));
    }//GEN-LAST:event_t18ActionPerformed

    private void NegritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegritoActionPerformed
        fonte = Font.BOLD;
        texto.setFont(new Font("",fonte,tam));
    }//GEN-LAST:event_NegritoActionPerformed

    private void italicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italicoActionPerformed
        fonte = Font.ITALIC;
        texto.setFont(new Font("",fonte,tam));
    }//GEN-LAST:event_italicoActionPerformed

    private void negritalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negritalicoActionPerformed
       fonte = Font.ITALIC+Font.BOLD;
        texto.setFont(new Font("",fonte,tam));
    }//GEN-LAST:event_negritalicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Limpar;
    private javax.swing.JCheckBoxMenuItem Negrito;
    private javax.swing.JRadioButtonMenuItem Preto;
    private javax.swing.JRadioButtonMenuItem azul;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBoxMenuItem italico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButtonMenuItem marrom;
    private javax.swing.JCheckBoxMenuItem negritalico;
    private javax.swing.JCheckBoxMenuItem normal;
    private javax.swing.JRadioButtonMenuItem rosa;
    private javax.swing.JCheckBoxMenuItem t12;
    private javax.swing.JCheckBoxMenuItem t14;
    private javax.swing.JCheckBoxMenuItem t16;
    private javax.swing.JCheckBoxMenuItem t18;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
