/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exemploradiocheckecombo;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Admin
 */
public class Exemplo extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo
     */
    public Exemplo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tamanho = new javax.swing.ButtonGroup();
        tamanho15 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        cor = new javax.swing.JComboBox<>();
        tamanho14 = new javax.swing.JRadioButton();
        tamanho16 = new javax.swing.JRadioButton();
        tamanho18 = new javax.swing.JRadioButton();
        texto = new javax.swing.JLabel();
        aplicar = new javax.swing.JButton();
        normal = new javax.swing.JCheckBox();
        negrito = new javax.swing.JCheckBox();
        italico = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tamanho12 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        tamanho.add(tamanho15);
        tamanho15.setText("14");
        tamanho15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanho15ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));

        cor.setMaximumRowCount(4);
        cor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Azul", "Amarelo", "Vermelho", "Verde" }));
        cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corActionPerformed(evt);
            }
        });

        buttonGroup1.add(tamanho14);
        tamanho14.setText("14");
        tamanho14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanho14ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tamanho16);
        tamanho16.setText("16");
        tamanho16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanho16ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tamanho18);
        tamanho18.setText("18");
        tamanho18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanho18ActionPerformed(evt);
            }
        });

        texto.setText("texto");

        aplicar.setText("Aplicar");
        aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarActionPerformed(evt);
            }
        });

        normal.setText("Normal");
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });

        negrito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        negrito.setText("Negrito");
        negrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negritoActionPerformed(evt);
            }
        });

        italico.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        italico.setText("Itálico");
        italico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italicoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cor");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tamanho");

        buttonGroup1.add(tamanho12);
        tamanho12.setText("12");
        tamanho12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanho12ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fonte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tamanho14)
                            .addComponent(tamanho12)
                            .addComponent(tamanho18)
                            .addComponent(tamanho16)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aplicar)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(texto)
                                .addGap(26, 26, 26)))
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(normal)
                            .addComponent(italico)
                            .addComponent(negrito)
                            .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tamanho12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tamanho14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tamanho16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tamanho18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(texto)
                        .addGap(34, 34, 34)
                        .addComponent(aplicar)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(normal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(negrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(italico)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tamanho14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanho14ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tamanho14ActionPerformed
    
    Integer estilo, tamfonte;
    
    private void aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarActionPerformed
       
        if(tamanho12.isSelected() == true){
            tamfonte = 12;
            texto.setFont(new Font("", estilo ,tamfonte));
       }
       if(tamanho14.isSelected() == true){
           tamfonte = 14;
           texto.setFont(new Font("", estilo ,tamfonte)); 
       }
       if(tamanho16.isSelected() == true){
           tamfonte = 16;
            texto.setFont(new Font("", estilo ,tamfonte));
       }
       if(tamanho18.isSelected() == true){
           tamfonte = 18; 
           texto.setFont(new Font("", estilo ,tamfonte));
       }
       
       if(cor.getSelectedItem().toString() == "Default"){
           texto.setForeground(Color.black);
       }
       if(cor.getSelectedItem().toString() == "Azul"){
            texto.setForeground(Color.blue);
       }
       if(cor.getSelectedItem().toString() == "Amarelo"){
           texto.setForeground(Color.yellow); 
       }
       if(cor.getSelectedItem().toString() == "Vermelho"){
            texto.setForeground(Color.red);
       }
       if(cor.getSelectedItem().toString() == "Verde"){
            texto.setForeground(Color.green);
       }
       
       
       
        
        aplicar.setToolTipText("Aplicará as opções selecionadas");
    }//GEN-LAST:event_aplicarActionPerformed

    private void corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corActionPerformed
         
    }//GEN-LAST:event_corActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        estilo=Font.PLAIN;
        italico.setSelected(false);
        negrito.setSelected(false);

    }//GEN-LAST:event_normalActionPerformed

    private void negritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negritoActionPerformed
        estilo=Font.BOLD;
        normal.setSelected(false);
        italico.setSelected(false);

    }//GEN-LAST:event_negritoActionPerformed

    private void italicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italicoActionPerformed
        // TODO add your handling code here:
        estilo=Font.ITALIC;
        negrito.setSelected(false);
        normal.setSelected(false);

    }//GEN-LAST:event_italicoActionPerformed

    private void tamanho16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanho16ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tamanho16ActionPerformed

    private void tamanho18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanho18ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tamanho18ActionPerformed

    private void tamanho15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanho15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamanho15ActionPerformed

    private void tamanho12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanho12ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tamanho12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cor;
    private javax.swing.JCheckBox italico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox negrito;
    private javax.swing.JCheckBox normal;
    private javax.swing.ButtonGroup tamanho;
    private javax.swing.JRadioButton tamanho12;
    private javax.swing.JRadioButton tamanho14;
    private javax.swing.JRadioButton tamanho15;
    private javax.swing.JRadioButton tamanho16;
    private javax.swing.JRadioButton tamanho18;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
